image: docker:19.03.13
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://localhost:2375
  TAG_LATEST: $CI_REGISTRY_IMAGE/$APP:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$APP:$CI_COMMIT_SHORT_SHA

services:
  - name: docker:19.03.13-dind
    command: ['--registry-mirror', 'https://mirror.gcr.io'] # Specify the registry mirror here


stages:
  - build


build-dev:
  variables:
    APP: front-dev
  stage: build
  environment: dev
  script:
    - echo -n $CI_BUILD_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $TAG_LATEST || true
    - docker build -t $TAG_LATEST -t $TAG_COMMIT .
    - docker push $TAG_LATEST
    - docker push $TAG_COMMIT



build-demo:
  variables:
    APP: front-demo
  stage: build
  environment: demo
  script:
    - echo -n $CI_BUILD_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $TAG_LATEST || true
    - docker build -t $TAG_LATEST -t $TAG_COMMIT --build-arg NUXT_API_BASE_URL='https://dev-panel.demo.projectrivers.com' .
    - docker push $TAG_LATEST
    - docker push $TAG_COMMIT
