image: docker:19.03.13
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  Novid: "2"
  DOCKER_HOST: tcp://localhost:2375
  TAG_LATEST: $CI_REGISTRY_IMAGE/$APP:latest
  TAG_BUILDER: $CI_REGISTRY_IMAGE/$APP:builder
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$APP:$CI_COMMIT_SHORT_SHA

services:
  - name: docker:19.03.13-dind
    command: ['--registry-mirror', 'https://mirror.gcr.io'] # Specify the registry mirror here


stages:
  - build


build-dev:
  variables:
    APP: front-dev
    Test: trigger
  stage: build
  script:
    - echo -n $CI_BUILD_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $TAG_LATEST || true
    - docker pull $TAG_BUILDER || true
    - docker build --target builder --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from=$TAG_BUILDER --tag $TAG_BUILDER .
    - docker build --target runner --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from=$TAG_BUILDER --cache-from=$TAG_LATEST --tag $TAG_LATEST --tag $TAG_COMMIT .
    - docker push $TAG_LATEST
    - docker push $TAG_COMMIT
    - docker push $TAG_BUILDER



build-demo:
  variables:
    APP: front-demo
  stage: build
  script:
    - echo -n $CI_BUILD_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $TAG_LATEST || true
    - docker pull $TAG_BUILDER || true
    - docker build --target builder --build-arg NUXT_API_BASE_URL='https://dev-panel-api.demo.lys.ice.global' --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from=$TAG_BUILDER --tag $TAG_BUILDER .
    - docker build --target runner  --build-arg NUXT_API_BASE_URL='https://dev-panel-api.demo.lys.ice.global' --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from=$TAG_BUILDER --cache-from=$TAG_LATEST --tag $TAG_LATEST --tag $TAG_COMMIT .
    - docker push $TAG_LATEST
    - docker push $TAG_COMMIT
    - docker push $TAG_BUILDER
    
    
build-fedshi-dev:
  variables:
    APP: front-fedshi-dev
  stage: build
  script:
    - echo -n $CI_BUILD_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $TAG_LATEST || true
    - docker pull $TAG_BUILDER || true
    - docker build --target builder --build-arg PROJECT_NAME='FEDSHI' --build-arg NUXT_API_BASE_URL='https://dev-panel-api.dev.fedshi.ice.global' --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from=$TAG_BUILDER --tag $TAG_BUILDER .
    - docker build --target runner --build-arg PROJECT_NAME='FEDSHI' --build-arg NUXT_API_BASE_URL='https://dev-panel-api.dev.fedshi.ice.global' --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from=$TAG_BUILDER --cache-from=$TAG_LATEST --tag $TAG_LATEST --tag $TAG_COMMIT .
    - docker push $TAG_LATEST
    - docker push $TAG_COMMIT
    - docker push $TAG_BUILDER

build-fedshi-demo:
  variables:
    APP: front-fedshi-demo
  stage: build
  script:
    - echo -n $CI_BUILD_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $TAG_LATEST || true
    - docker pull $TAG_BUILDER || true
    - docker build --target builder --build-arg PROJECT_NAME='FEDSHI' --build-arg NUXT_API_BASE_URL='https://dev-panel-api.demo.fedshi.ice.global' --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from=$TAG_BUILDER --tag $TAG_BUILDER .
    - docker build --target runner --build-arg PROJECT_NAME='FEDSHI' --build-arg NUXT_API_BASE_URL='https://dev-panel-api.demo.fedshi.ice.global' --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from=$TAG_BUILDER --cache-from=$TAG_LATEST --tag $TAG_LATEST --tag $TAG_COMMIT .
    - docker push $TAG_LATEST
    - docker push $TAG_COMMIT
    - docker push $TAG_BUILDER

